### ISSUE TITLE
custom taxonomy, change order and order by

### ISSUE THREAD

**Issue by gaspas** [wordplate/extended-acf#111]
hello, I'am trying to change the order and orderby in the loop of a custom taxonomy.

`function topico_pre_get_posts( $query ){

    if( !is_admin() && is_tax('topico') && $query->is_main_query() && $query->is_tax() ){

    	$order = isset($_POST['order_custom']) ? $_POST['order_custom'] : 'DESC';
        
        $query->set('acfe_single_order', $order); 
		$query->set('acfe_single_orderby', 'title');

        return $query;
    }
}
add_action( 'pre_get_posts', 'topico_pre_get_posts' );`

It seems that acfe_single_orderby and acfe_single_order can't be overridden. Or do I miss something!

Thanks

**Comment by fiskhandlarn** [comment]
@gaspas 
1. what is "acf**e**_single_order"?
2. this package does absolute nothing with the `pre_get_posts` hook, so this issue is probably outside of it's scope. can you reproduce this issue without using `wordplate/extended-acf`?

**Comment by vinkla** [comment]
As @fiskhandlarn already has stated, this doesn't seem to be an issue with this package.
