### ISSUE TITLE
Layout for Radio field missing

### ISSUE THREAD

**Issue by ernilambar** [wordplate/extended-acf#59]
## Expected Behavior
`layout()` field is needed in Radio field.
## Actual Behavior

For Radio field, `layout()` is missing.

## Steps to Reproduce the Problem

  1. Radio::make('Sample')->layout('horizontal')

## Versions

  - WordPlate: 5.4
  - PHP: 7.2

**Comment by vinkla** [comment]
Thanks for pointing it out! Please submit a pull request adding this feature.

**Comment by vinkla** [comment]
Closed in #60
