### ISSUE TITLE
Bad return on the call of a repeater generate

### ISSUE THREAD

**Issue by AlexVWeb** [wordplate/extended-acf#68]
## Predictable behavior
I should have a table with my different fields included in my repeater.

## Actual behavior
I get the number of elements to create
when I dump:
`dump ($match, get_field ('site', $match-> ID));`
I take back
`" 1 "`

instead of retrieving with the same fields generate in the ACF administration:
`
0 => [
     "url" =>  [
       "title" => "Home"
       "url" => "// localhost: 3000 /"
       "target" => ""
     ]
     "logo" =>  []
   ]
`

## Steps to reproduce the problem
I can't reproduce the bug

## Versions
    - WordPlate: ^ 8.4
    - PHP: ^ 7.3

**Comment by vinkla** [comment]
Please make your issue more informative. Thanks don't understand your problem. 

Also, try registering your fields with the UI and see if that works first.

**Comment by AlexVWeb** [comment]
With the code below, I want to recover the "Sport" taxonomy in "Object" format, the problem is that I receive at the output only the ID, while the same form done with the administration of ACF works.

```
register_extended_field_group([
    'title' => 'Sport',
    'location' => [
        Location::if('taxonomy', 'championship')
    ],
    'fields' => [
        Taxonomy::make('Sport', 'sport')
            ->returnFormat('object')
            ->taxonomy('sport')
            ->loadTerms()
            ->saveTerms()
            ->createTerms()
            ->appearance('select'),
    ],
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => PARAMS['hide_all_screen'],
    'description' => '',
]);
```

```
dump(get_field('sport', $match['championship']));
```
I only get the ID when normally I would get the WP_Term

I have the same problem with several other "Fields", but on another project everything worked fine!

(Translated from French)

**Comment by vinkla** [comment]
Does it work if you register your fields with the UI instead of this package?

**Comment by AlexVWeb** [comment]
> Does it work if you register your fields with the UI instead of this package?

Yes it works very well with the UI interface, this problem also happens to me with the Repeaters, when I do a 
```php
get_field('repeater', $ post_id)
 ``` 
on a Repeater Wordplate it returns the ID, whereas with the UI interface it returns the content of the elements of my repeater

**Comment by vinkla** [comment]
Okay, then it could be an issue with this package. Have you looked into the source code and see if you could find the issue?

**Comment by vinkla** [comment]
What is the output of following code in your project? We just need to confirm we get the correct field data.

```php
$field = Taxonomy::make('Sport', 'sport')
  ->returnFormat('object')
  ->taxonomy('sport')
  ->loadTerms()
  ->saveTerms()
  ->createTerms()
  ->appearance('select');

dump($field->toArray());
```

**Comment by vinkla** [comment]
Just tried this locally and it seems to work if you remove `loadTerms`.
