### ISSUE TITLE
Additional Config Settings

### ISSUE THREAD

**Issue by zangab** [wordplate/extended-acf#77]
## Expected Behavior

Out of curiosity I tried the acf-extended plugin (https://www.acf-extended.com/features/fields/flexible-content), especially the flexible-content feature where u can have a modal as a layout-picker instead of a lousy tooltip. However, I have no option to add any custom config key/values to ANY field and this is actually a problem.

## Actual Behavior

I am able to add custom config key-values with a function. 
I mean, i can re-create my own "flexible-content" and "layout" field and call the `$this->config->set('key', 'value');` but, well, kinda ugly.

## Steps to Reproduce the Problem

  1. install / enable acf-extended
  2. use UI to create modal picker (need at least 2 layouts)
  3. can't recreate the modal with code only, as custom config keys are necessary for this

## Versions

  - WordPlate: 8.5
  - PHP: 7.4

**Comment by vinkla** [comment]
I understand the confusion but `acf-extended` and `extended-acf` is not the same project.
