### ISSUE TITLE
Cannot disable the Taxonomy field's add_term option

### ISSUE THREAD

**Issue by josephfusco** [wordplate/extended-acf#82]
I can see that this library's `Taxonomy::createTerm` method is a wrapper for ACF's `add_term`.
Since this is an additive option, I was expecting new term creation to be disabled while editing if createTerm wasn't used.
Looking at the [official ACF docs for registering fields via php](https://www.advancedcustomfields.com/resources/register-fields-via-php/#relational), it appears that `add_term` is true by default.

## Expected Behavior

Should **Allow** terms to be created whilst editing.

```php
Taxonomy::make('My Taxonomy')
  ->taxonomy('my_taxonomy')
  ->createTerms();
```

Should **Not allow** terms to be created whilst editing.

```php
Taxonomy::make('My Taxonomy')
  ->taxonomy('my_taxonomy');
```

## Actual Behavior

**Allows** terms to be created whilst editing.

```php
Taxonomy::make('My Taxonomy')
  ->taxonomy('my_taxonomy')
  ->createTerms();
```

**Allows** terms to be created whilst editing.

```php
Taxonomy::make('My Taxonomy')
  ->taxonomy('my_taxonomy');
```

## Versions

  - WordPlate: 5.5.3
  - PHP: 7.4.12

Thank you and terrific job with this package! 🙌🏼

**Comment by vinkla** [comment]
Thanks for looking into this. I wonder if we could provide a better developer experience here. The method `createTerms` doesn't really describe itself. Maybe we should rethink these and look at the default values once again. All term methods would probably be better of with new names:

```php
->createTerms() // Allow new terms to be created whilst editing
->loadTerms() // Load value from posts terms
->saveTerms() // Connect selected terms to the post
```

> Thank you and terrific job with this package! 🙌🏼

Thanks for saying that! I'm glad you like it.

**Comment by josephfusco** [comment]
Hey @vinkla thanks for the quick reply! I agree with potentially improving the developer experience here.

It looks like [these are the current defaults](https://github.com/AdvancedCustomFields/acf/blob/37fcf7204f034c0dcdf8240ffa6d802a238431dc/includes/fields/class-acf-field-taxonomy.php#L30-L39) for ACF's taxonomy field.

```php
'add_term'   => 1, // Allow new terms to be created whilst editing.
'load_terms' => 0, // Load value from posts terms.
'save_terms' => 0, // Connect selected terms to the post.
```

## Option 1

Descriptive names that negate the ACF defaults. There are no arguments here which is nice but these methods would need to be updated if the default values from ACF change again.

```php
Taxonomy::make('My Taxonomy')->disableAddTerm();
Taxonomy::make('My Taxonomy')->loadTermsFromPost();
Taxonomy::make('My Taxonomy')->saveTermsToPost();
```

## Option 2

This option provides a 1:1 match with the language ACF uses (add_term, load_term, save_term). There is less thinking involved here for developers that may just be discovering this library but are already familiar with ACF. We can future proof these methods from by requiring a boolean to be passed in.

```php
Taxonomy::make('My Taxonomy')->addTerm(bool);
Taxonomy::make('My Taxonomy')->loadTerms(bool);
Taxonomy::make('My Taxonomy')->saveTerms(bool);
```

I'd love to hear your thoughts @vinkla and any other options or variations of the above you can think of. I'll be happy to update my [current pull request](https://github.com/wordplate/extended-acf/pull/83/files) with whatever is decided.

**Comment by vinkla** [comment]
Thanks for taking the time to dig into this Joseph!

IMO option 2 looks more appropriate since it follows the pattern of other methods in this library. The reason we decided on `createTerms` instead of `addTerm` was because the ACF UI use this copy in the dashboard. It makes sense renaming it `addTerm` and follow the naming convention in ACF. Even though the naming convention isn't very clear/understandable at first sight.

<img src="https://user-images.githubusercontent.com/499192/99874675-1afc0e00-2bea-11eb-9d6a-a494367c3a62.png" width="350">

> We can future proof these methods from by requiring a boolean to be passed in.

I think the option to allow a boolean would be great and we could provide the default value.
 
> I'll be happy to update my current pull request with whatever is decided.

That would be great!

**Comment by josephfusco** [comment]
@vinkla The previous [pull request](https://github.com/wordplate/extended-acf/pull/83/files) has been updated and is ready for your consideration.
