### ISSUE TITLE
WYSIWYG field : Use custom toolbar

### ISSUE THREAD

**Issue by jbbouchet** [wordplate/extended-acf#84]
## Expected Behavior

Hello everyone,

According to the ACF [documentation](https://www.advancedcustomfields.com/resources/customize-the-wysiwyg-toolbars/), you can define a custom toolbar in WYSIWYG field. Currently, you can define toolbar in **extended-acf** with `->toolbar(string $toolbar)` in `Wysiwyg` class.

If you create a new toolbar with the name **_Very Simple_** (as in the ACF cookbook), and you try to pass the same name in `Wysiwyg` toolbar method, nothing happens, because ACF use snake case version of name to define which element is used.

<img width="1139" alt="toolbar-acf" src="https://user-images.githubusercontent.com/4848626/101197759-d6995500-3662-11eb-8f2c-eaff3f8c88ab.png">

My question is : it is the code's responsibility to turn all names into a snake case version, or the documentation for this project should be more explicit ?

## Actual Behavior

`->toolbar(string $toolbar)` supports only snake case names.

## Versions

  - WordPlate: 8.5.0
  - PHP: 7.3

**Comment by vinkla** [comment]
Thanks for reporting this Jean-Baptiste. In this case I think we can simply add a comment to the documentation. Do you mind sending a pull request? Maybe something like:

```php
->toolbar('simple') // toolbar name in snake_case
```

**Comment by jbbouchet** [comment]
@vinkla , of course PR is open! Have a nice day.

**Comment by vinkla** [comment]
Fixed in #85
